### ISSUE TITLE
Replace hamburger menu link with correct url

### ISSUE THREAD

**Issue by KarnellSchultz** [tracits/rodant#102]
When clicking the nav hamburger menu, you're directed to http://titco.org/ which is a blank page. 

It appears that this link is intended to point to the home page.

**Comment by martingerdin** [comment]
I suggest removing or hiding the hamburger menu until we’ve got something to put there.

**Comment by KarnellSchultz** [comment]
Removed the hamburger menu. Refactored the <nav />'s CSS and HTML. changed the style of the 'records' link to make it look more like a button located in the nav. Open to feedback about this change.

![localhost_3000_ (1)](https://user-images.githubusercontent.com/50870173/86022720-08aae900-ba2b-11ea-8cb1-79d0e69f3902.png)
