### ISSUE TITLE
Add Built with Rodant vX.Y.Z

### ISSUE THREAD

**Issue by martingerdin** [tracits/rodant#106]
The Rodant version is currently shown directly after the tool name. I think it would make more sense to visually separate the Rodant version from the tool/instance version (which may be different). I therefore suggest that we put "Built with Rodant (X.Y.Z)" or something along those lines somewhere else on the the page, perhaps to the far right of the top bar.

**Comment by KarnellSchultz** [comment]
Fixed in - #115
