### ISSUE TITLE
Record created with only UID, all other variables named <unset>

### ISSUE THREAD

**Issue by tracits** [tracits/rodant#125]
For site 1824, there's one record in the exported .csv file that has auid 1369, but no other variables are set. Unsure how this could happen. (It does crash the import on the backend site since <unset> is interpreted as a string.)

When importing this dataset to rodant, the record can not be found by searching all fields for the uid.

**Comment by KarnellSchultz** [comment]
Hey - I tried to reach out about this in our slack.

I'm not sure if I follow how to reproduce the issue. Mind giving me some steps to replicate? Any relevant  screenshots could be helpful too. 

Thanks

**Comment by KarnellSchultz** [comment]
Think we can close this issue since we've not been able to replicate it.

**Comment by tracits** [comment]
So this happens when you just create a record, and then close it. Since we changed the output from "<unset>" to NULL in the csv exports however, it does not effect the import backend any more. Also, we chose this behaviour, that a record that is not completed and missing mandatory information is still saved, so, I think this behaviour should now be considered expected. Agreed?

**Comment by martingerdin** [comment]
The problem is that it’s not possible to find these records using the tool,
so there’s no way to delete them (except by exporting the database,
deleting the records, and then importing the database again). I suggest
that we modify the behavior so that these empty records are not saved.

**Comment by tracits** [comment]
You can't search for them, because the uid is not searchable, you will however see them when you list all records, you will se records with no pid and errors only. Here you're able to delete them.

However, I agree that a more correct behaviour is that a record that has only been created and contains no data, should not be saved when you press "Close record".

**Comment by martingerdin** [comment]
Of course, you’re right. And I agree that an empty record should not be
saved when the user clicks close record or close the tab. I suggest that we
close this issue and open a new. What do you think?

**Comment by tracits** [comment]
Agreed! Doing it now!
