### ISSUE TITLE
Sort id variable as numeric

### ISSUE THREAD

**Issue by martingerdin** [tracits/rodant#128]
After the last update the id variable is no longer sorted as numeric.
![8B2AE145-8759-451A-9208-FAEFA55525E3](https://user-images.githubusercontent.com/17697460/92299259-0300e080-ef51-11ea-9427-8914ad6a27ec.jpeg)

**Comment by KarnellSchultz** [comment]
Looks like the numeric sort is based on the first digit of the id.
