### ISSUE TITLE
Records containing no data should not be saved

### ISSUE THREAD

**Issue by tracits** [tracits/rodant#132]
Current behaviour, if the user adds a new record and immediately closes it, it will be saved with a UID but with all variables empty. This is then exported as empty records. 
Suggested solution, if a record has been created but is empty, it's not saved when the user closes the record.

**Comment by KarnellSchultz** [comment]
Is there a minimum amount of data we'd like the have before being able to save the record? 
Specifically thinking do we want to make sure there is a PID or Center ID or something like that before it's worth saving?

**Comment by martingerdin** [comment]
I think it makes sense that the id variable is completed before it’s
possible to save a record. The id variable is specified in the config
file.

**Comment by martingerdin** [comment]
Fixed by #133
