### ISSUE TITLE
Add button to unlock all records

### ISSUE THREAD

**Issue by itslwg** [tracits/rodant#153]
Atm, you have to unlock record by record. More convenient if that could be done in one sweep.

**Comment by tracits** [comment]
I’m not sure about this functionality, a locked record is a record that is complete and where all data has been double entered. A record should only be unlocked in very special circumstances, the rule is that it should not happen at all once a record is locked.

**Comment by itslwg** [comment]
Aha, fair enough. For me it was for debugging purposes, for #143 , but considering that they really shouldnt be unlocked it is  probably not a good idea. Closing for now.
