### ISSUE TITLE
Upload data to back-end servers

### ISSUE THREAD

**Issue by tracits** [tracits/rodant#22]
KI servers use Web-dav for communication. Ongoing discussions with KI if any other solution is possible. Issue pending information from KI.

As of now, only level 2 data should be uploaded (I.e, not sensitive personal data.)

**Comment by martingerdin** [comment]
We currently use indexeddb for local storage but need to add a module that allows syncing local data with a remote server. PouchDB locally and CouchDB remotely is one attractive options. Other solutions include uploading to Nextcloud remotely using WebDAV or their JavaScript API.

**Comment by martingerdin** [comment]
Closing this, refer to #100 for continued work
