### ISSUE TITLE
Add link to github release notes

### ISSUE THREAD

**Issue by martingerdin** [tracits/rodant#98]
Either directly from the version number or if we add a separate button to do this, What's new?

**Comment by KarnellSchultz** [comment]
Mind clarifying the URL you'd like the version number to link to? is it 'https://github.com/tracits/rodant/blob/master/CHANGELOG.md' ?

**Comment by martingerdin** [comment]
Yes, that works!

**Comment by martingerdin** [comment]
Fixed
